version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "18:00"
    timezone: Asia/Taipei
  versioning-strategy: increase
  open-pull-requests-limit: 50
