name: Black cat CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache Docker build
      uses: actions/cache@v1
      with:
        path: /var/lib/docker
        key: ${{ runner.OS }}-cache-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.OS }}-cache-
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag blackcat:$(date +%s)
