name: Black cat GitHub Workflow

on:
  push:
    branches:
      - main
      - stable
  pull_request:
    branches:
      - main
      - stable

jobs:
  update-lockfile:
    name: Update lockfile
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup Node.js runtime
      uses: actions/setup-node@v2
      with:
        node-version: "14.16.1"
    - name: Cache packages
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install latest yarn
      run: npm i yarn -g
    - name: Install packages to generate lock file
      run: yarn install --ignore-engines
    - name: Commit modified lock file
      uses: EndBug/add-and-commit@v7
      with:
        add: yarn.lock
        default_author: github_actions
        message: "Update lockfile"
  check-docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: update-lockfile
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag blackcat:latest
    - name: Inspect Docker image
      run: docker inspect -f "{{ .Size }}" blackcat:latest | numfmt --to=si
    - name: Run test script
      run: docker run -t --rm --name blackcat-ci blackcat:latest yarn run test
  check-standard:
    name: Check node.js syntax
    runs-on: ubuntu-latest
    needs: update-lockfile
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: "14.16.1"
    - name: Cache packages
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install latest yarn
      run: npm i yarn -g
    - name: Install packages
      run: yarn install --frozen-lockfile --ignore-engines
    - name: Test syntax
      run: yarn run test
  analyze:
    name: Run code QL scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: javascript
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
