name: Black cat GitHub Workflow

on:
  push:
    branches:
      - main
      - stable
  pull_request:
    branches:
      - main
      - stable

jobs:
  update-lockfile:
    name: Update package-lock.json
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js runtime
      uses: actions/setup-node@v2
      with:
        node-version: "14.16.1"
    - name: Cache npm packages
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
          ~/.npm
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install latest npm
      run: npm install npm -g
    - name: Install packages to generate lock file
      run: npm install
    - name: Commit modified lock file
      uses: EndBug/add-and-commit@v7
      with:
        add: package-lock.json
        default_author: github_actions
        message: "Update package-lock.json"
  check-docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: update-lockfile
    steps:
    - uses: actions/checkout@v2
    - name: Cache Docker layer
      uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag blackcat:latest
    - name: Run test script
      run: docker run -t --rm --name blackcat-ci blackcat:latest bash bootstrap.sh test
  check-standard:
    name: Check node.js syntax
    runs-on: ubuntu-latest
    needs: update-lockfile
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js V.${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: "14.16.1"
    - name: Cache npm packages
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
          ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install latest npm
      run: npm install npm -g
    - name: Install packages
      run: npm install
    - name: Test syntax
      run: bash bootstrap.sh test
  analyze:
    name: Code QL analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: javascript
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
